name: Dependency Graph Submission

on:
  push:
    branches: [ "master" ]

jobs:
  dependency-submission:
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Generate and Submit Dependency Graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582
